### ISSUE TITLE
'setDescription(com.github.mikephil.charting.components.Description)' in 'com.github.mikephil.charting.charts.Chart' cannot be applied to '(java.lang.String)'

### ISSUE THREAD

**Issue by jmparola** [mitchtabian/Pie-Chart-Tutorial#1]
why do this shows an error? pls help

**Comment by mitchtabian** [comment]
Looks like you are trying to apply "setDescription" to a String. This is not a bug.

**Comment by jmparola** [comment]
how can i correct this ?? thanks a lot.. im studying this graphs for my project.. by using graphs to android from a fireabse database..

**Comment by mitchtabian** [comment]
Sounds like a cool project. Firebase is a great way to do it. You could easily get a live feed for a graph.

As for your problem, like I said it looks like your using setDescription on a string. But you need to use it on a chart object.

**Comment by jmparola** [comment]
thanks.. :) do you have a tutorial on a graph connected to firebase??  this would help me a lot if you have one. thanks again.

**Comment by mitchtabian** [comment]
Hey,
No I don't unfortunately. But it would be very easy to do since firebase is
a real-timr database.

Just add the data points to the graph from the firebase database.

Store the data points as data point objects.

--Mitch

**Comment by jmparola** [comment]
thanks again..  i hope i can find one tutorial.. thanks for the help. :)
keep safe!
